apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db
  name: pvc-docker-entrypoint-db-v2
  namespace: wieisdetrol
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
