apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: bot
  name: pvc-bot-v2
  namespace: wieisdetrol
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
